### ISSUE TITLE
Integrate an agent server

### ISSUE THREAD

**Issue by cowboyd** [bigtestjs/server#15]
We're clear that one of the moving pieces is the BigTest agent which will be active inside the browser process that is actually running the test. It will be served from the bigtest server over http so that it can be injected as a script, for example `http://localhost:4003/agent.js`

That means that this code has its own entry point, and will need to be assembled independently from the server along with its own unique set of (possibly overlapping) dependencies.

In the production version of the agent that is published on NPM, we'll want to pre-compile this agent code from TypeScript and bundle all its pieces ahead of time and just have a static file server serving it. However, when developing the server itself, we'll need a mechanism to watch the files that comprise the agent, and rebuild the agent bundle any time that they change.

**Comment by jnicklas** [comment]
Assigning myself to this :)
