### ISSUE TITLE
Make orchestrator capable of starting the application

### ISSUE THREAD

**Issue by cowboyd** [bigtestjs/server#40]
Current process:

```
$ yarn start
$ cd ../my-app
$ PORT=24000 yarn start
```

MVP process:

```
$ cd my--app
$ yarn bigtest --start-with 'yarn start' --app-url http://localhost:3000
```

This implies that the orchestrator will be able to

1. start the app
2. wait until the app is running at the specified port before being considered ready.

For testing purposes, we'll need to use the example app.

**Comment by jnicklas** [comment]
This was completed by #45
