### ISSUE TITLE
Add TodoMVC app as a fixture for the test suite 

### ISSUE THREAD

**Issue by cowboyd** [bigtestjs/server#41]
In order to do development, and also have a test suite, we need to have an application of non-trivial complexity that's not to difficult to maintain. This will be critical for automated testing too.

We should be able add a `todomvc` script to `package.json` that can be used to start our server.

```
$ yarn todomvc -p 3000
```

That way, when we run in development we can start the server conveniently like:

```
$ yarn start --start-with 'yarn todomvc -p 3000'
```

In our test suite, we can also start our app and then run the components of the system against it.

### Constraints

* It should be just a pre-built, vendored app that can be served in its entirety

**Comment by jnicklas** [comment]
There is now a fixture included, but it is dynamically built. This makes the test suite slower to start, but also somewhat more realistic, so I'm not sure if we want to mark this as done? Maybe we should make a new issue for pre-compiling the test app?

**Comment by cowboyd** [comment]
That's a great idea. There's a lot of precompilation tasks that we need to think about. I'll try and compile a list of issues related.
